[project]
name = "taxes-calculator"
version = "0.1.0"
description = "Program that keep traces of income and calculate taxes you need to pay for your Italian Partita Iva"
readme = "README.md"
authors = [
    { name = "marco", email = "marcocoppola01671@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
]

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "app"
module-root = ""
