[project]
name = "taxes-calculator"
version = "0.1.0"
description = "Program that keep traces of income and calculate taxes you need to pay for your Italian Partita Iva"
readme = "README.md"
authors = [
    { name = "marco", email = "marcocoppola01671@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "psycopg2-binary>=2.9.13",
    "python-dotenv>=1.2.3",
    "sqlalchemy>=2.0.54",
    "uvicorn>=0.53.0",
]

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "app"
module-root = ""

[tools.fastapi]
entrypoint = "app.main:app"
